/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#1A1A2E',
        'secondary': '#E84855',
        'tertiary': '#2EC4B6',
        'primary-container': '#1A1A2E',
        'on-primary': '#ffffff',
        'on-primary-container': '#83829b',
        'secondary-container': '#ff5964',
        'on-secondary-container': '#600012',
        'tertiary-fixed': '#2EC4B6',
        'tertiary-fixed-dim': '#4fdbcc',
        'on-tertiary-container': '#009589',
        'surface': '#f9f9fb',
        'surface-bright': '#f9f9fb',
        'surface-dim': '#d9dadc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f5',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e4',
        'on-surface': '#1a1c1d',
        'on-surface-variant': '#47464c',
        'outline': '#78767d',
        'outline-variant': '#c8c5cd',
        'inverse-surface': '#2f3132',
        'inverse-on-surface': '#f0f0f2',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'background': '#f9f9fb',
        'on-background': '#1a1c1d',
      },
      fontFamily: {
        headline: ['"DM Serif Display"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
